### PR TITLE
Corrected location response

### PR DESCRIPTION
**Pull request by AliAyub007**
Fixes issue #18 

Changes: 
Corrected location response

Screenshots for the change: 
21122850_865109010306874_439400087_o

### CODE REVIEW

**Comment by AliAyub007** [comment]
@betterclever @saurabhjn76 Kindly review this PR Thanks.

**Review by saurabhjn76 — APPROVED** [review]

**Comment by mariobehling** [comment]
Why is there a loklak logo instead of a SUSI AI logo?

**Comment by AliAyub007** [comment]
@mariobehling  I already have updated this in morning in the screenshot. It's not updated it got updated after a while in the client. 

See this 
21122921_865176213633487_1307356001_o

**Comment by mariobehling** [comment]
Thanks.

**Pull request merged**
